Repository PurotoApp/newUI, pull requests merged in 2022-05, with the labels that each got.

#11 added dependabot config
  .github/dependabot.yml
Labels: enhancement

#4 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 📝 documentation

#9 Create pull_request_template.md
  .github/pull_request_template.md
Labels: 📝 documentation

#10 :sparkles: Added utility makefile
  makefile
Labels: 🔨 scripts

#5 :truck: Organized md files
  docs/INSTALL.md
  docs/README.md
Labels: 📝 documentation

#16 :heavy_plus_sign: Added scss loader
  package.json
  yarn.lock
Labels: ✨ enhancement

#19 :adhesive_bandage: Fixing patreon link
  CONTRIBUTING.md
Labels: 📝 documentation, 🐛 bug Fix

#18 :wrench: Adding Linting
  .editorconfig
  .eslintrc.js
  .github/workflows/eslint.yml
  .prettierrc
  CODE_OF_CONDUCT.md
  docs/INSTALL.md
  docs/README.md
  makefile
  nuxt.config.ts
  package.json
  yarn.lock
Labels: 👷 CI, 🔧 config, 🔨 scripts
